/**
 * Keyword lists for the simple mood classifier (docs/SPEC.md §15, docs/DESIGN.md §11). Data only.
 *
 * Matching rules (see classifyMood.ts), applied after NFKC + lowercase + U+FE0F removal:
 *  - *_KEYWORDS: ASCII entries match at a leading word boundary (stem: "thank" hits "thanks");
 *    non-ASCII entries (Japanese, accented Latin, emoji) match as plain substrings.
 *  - *_WHOLE_WORDS: ASCII only, must match a complete word (leading AND trailing boundary), used where
 *    a stem would hit unrelated words ("fun" vs "fund", "cry" vs "crypto", "glad" vs "gladiator").
 *
 * Known limits: negation is not handled ("好きじゃない", "not happy" still count "好き" / "happy").
 * Deliberate exclusions (too ambiguous): single "w" / "ww" (matches URLs "www."), 草 alone (grass),
 * 愛 (愛知), 辛い (spicy food), 眠い/sleepy (mild, not an emotion signal), bare profanity such as
 * "fuck"/"shit" (emphatic in both directions), 🥺 😅 🥹 😤 (ambiguous emoji), "sorry", "hope".
 */

export const POSITIVE_KEYWORDS: readonly string[] = [
  // Japanese
  "ありがと",
  "おめでと",
  "感謝",
  "最高",
  "最強",
  "嬉し",
  "うれし",
  "楽し",
  "たのし",
  "好き",
  "大好",
  "かわいい",
  "可愛",
  "すごい",
  "凄い",
  "素敵",
  "すてき",
  "幸せ",
  "しあわせ",
  "感動",
  "癒",
  "よかった",
  "良かった",
  "美味し",
  "おいし",
  "面白い",
  "おもしろ",
  "尊い",
  "わーい",
  "やった",
  "大草原",
  "草生え",
  "笑",
  "♪",
  // English (stems, leading boundary)
  "love",
  "lovin",
  "happy",
  "happi",
  "great",
  "awesome",
  "amazing",
  "wonderful",
  "beautiful",
  "gorgeous",
  "adorable",
  "fantastic",
  "brilliant",
  "excit",
  "congrat",
  "thank",
  "grateful",
  "blessed",
  "yay",
  "haha",
  "cute",
  "perfect",
  "proud",
  "delight",
  "enjoy",
  // Portuguese
  "obrigad",
  "feliz",
  "lindo",
  "linda",
  "parabéns",
  "parabens",
  "ótimo",
  "otimo",
  "maravilh",
  // Spanish
  "gracias",
  "genial",
  "hermos",
  "felicidades",
  "excelente",
  // Emoji (U+FE0F is stripped, so base characters are listed)
  "😊",
  "😄",
  "😁",
  "😆",
  "😀",
  "😃",
  "😉",
  "😎",
  "🤣",
  "😂",
  "🥰",
  "😍",
  "❤",
  "💕",
  "💖",
  "💗",
  "💙",
  "💜",
  "💚",
  "💛",
  "🧡",
  "✨",
  "🎉",
  "🥳",
  "👍",
  "🙏",
  "🌸",
  "🌈",
];

export const POSITIVE_WHOLE_WORDS: readonly string[] = [
  // English
  "good",
  "nice",
  "best",
  "fun",
  "funny",
  "glad",
  "joy",
  "lol",
  "lmao",
  "sweet",
  "yum",
  // Portuguese / Spanish (short words that are prefixes of unrelated words, e.g. "amount")
  "amo",
  "amei",
  "amor",
];

export const NEGATIVE_KEYWORDS: readonly string[] = [
  // Japanese
  "疲れ",
  "疲労",
  "つかれ",
  "しんどい",
  "つらい",
  "つらすぎ",
  "悲し",
  "かなしい",
  "最悪",
  "最低",
  "嫌い",
  "きらい",
  "嫌だ",
  "いやだ",
  "むかつ",
  "ムカつ",
  "腹立",
  "怒",
  "不安",
  "寂し",
  "さみし",
  "憂鬱",
  "鬱",
  "死にたい",
  "泣きたい",
  "泣いた",
  "泣いて",
  "泣きそう",
  "絶望",
  "もう無理",
  "無理すぎ",
  "無理だ",
  "だるい",
  "痛い",
  "苦しい",
  "ひどい",
  "酷い",
  "怖い",
  "こわい",
  "残念",
  "悔しい",
  "落ち込",
  "うざ",
  "地獄",
  // English (stems, leading boundary)
  "angry",
  "anger",
  "hate",
  "hatred",
  "tired",
  "exhaust",
  "awful",
  "terrible",
  "horrible",
  "horrific",
  "worst",
  "depress",
  "anxi",
  "lonel",
  "miser",
  "upset",
  "furious",
  "disgust",
  "annoy",
  "frustrat",
  "stressed",
  "stressful",
  "sick of",
  "fed up",
  "scared",
  "afraid",
  "worried",
  "heartbroken",
  "devastat",
  "painful",
  "hurt",
  // Portuguese
  "triste",
  "odeio",
  "cansad",
  "raiva",
  "péssimo",
  "pessimo",
  // Spanish
  "odio",
  "enojad",
  // Emoji
  "😢",
  "😭",
  "😞",
  "😔",
  "😩",
  "😫",
  "😡",
  "😠",
  "🤬",
  "💔",
  "😰",
  "😱",
  "😖",
  "😣",
  "😓",
  "😟",
  "😨",
  "🤮",
  "🥀",
  "👎",
];

export const NEGATIVE_WHOLE_WORDS: readonly string[] = [
  "sad",
  "sadly",
  "sadness",
  "bad",
  "cry",
  "cries",
  "cried",
  "crying",
  "suck",
  "sucks",
  "ugh",
  "pain",
];
